site:
  title: Rudder Documentation
  start_page: get-started::index
content:
  sources:
  - url: .
    branches: HEAD
    start_path: src/get-started
  - url: .
    branches: HEAD
    start_path: src/rudder-by-example
  - url: .
    branches: HEAD
    start_path: src/reference

