site:
  title: Rudder Documentation
  start_page: get-started::index
  url: https://docs.rudder.io
content:
  sources:
  - url: .
    branches: master
    start_path: src/get-started
  - url: .
    branches: master
    start_path: src/rudder-by-example
  - url: ./doc-5.0
    branches: "5.0"
    start_path: src/reference

