site:
  title: Rudder Documentation
  start_page: get-started::index
content:
  sources:
  - url: ../
    branches: HEAD
    start_path: unified/rudder-by-example
  - url: ../
    branches: HEAD
    start_path: unified/get-started
